(define (multiple-dwelling)
  (let ((cooper (amb 1 2 3 4 5))
        (fletcher (amb 1 2 3 4)))
    (require (not (= cooper fletcher)))
    (require (not (= cooper 1)))
    (require (not (= fletcher 1)))
    (require (not (= fletcher 5)))
    (require ((not (= (abs (- fletcher cooper) 1)))))
    (let ((smith (amb 1 2 3 4 5)))
      (require (distinct (list cooper fletcher smith)))
      (require (not (= (abs (- smith fletcher)) 1)))
      (let ((miller (amb 1 2 3 4 5)))
        (require (distinct (list cooper fletcher smith miller)))
        (require (> miller cooper))
        (let (baker (amb 1 2 3 4 5))
          (require
            (distinct? (list baker cooper fletcher miller smith)))
          (require (not (= baker 5)))
          (list (list 'baker baker)
                (list 'cooper cooper)
                (list 'fletcher fletcher)
                (list 'miller miller)
                (list 'smith smith)))))))
